export const GET = '/pokemons'
export const GETID = '/pokemons/'
export const GETNAME = '/pokemons/?name='
export const POST = '/pokemons'
export const TYPESURL = '/pokemons/types'
export const DELETE = '/pokemons/delete/'